name: "sdf-install"
description: "Run common installation steps for a NetSuite SDF Project"
runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "oracle"
    - name: Install package
      run: npm i --acceptsuitecloudsdklicense --legacy-peer-deps
      shell: bash
    - name: prettier check
      run: npx prettier . --check
      shell: bash
    - name: Authenticate project against
      run: npm run saveAuth -- --authtype prod
      shell: bash
    - name: Remove Private Key File
      if: always()
      run: rm -f private_key.pem
      shell: bash
